import os
import json
from supabase import create_client, Client
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")

if not url or not key:
    print("Error: SUPABASE_URL or SUPABASE_KEY not found.")
    exit(1)

supabase: Client = create_client(url, key)

def import_data():
    json_path = "frontend/src/data/crime_data.json"
    
    if not os.path.exists(json_path):
        print(f"Error: {json_path} not found.")
        return

    with open(json_path, 'r') as f:
        data = json.load(f)

    print(f"Read {len(data)} records from {json_path}")

    # Batch insert
    batch_size = 100
    for i in range(0, len(data), batch_size):
        batch = data[i:i+batch_size]
        try:
            response = supabase.table("crime_data_archive").insert(batch).execute()
            print(f"Inserted batch {i//batch_size + 1}")
        except Exception as e:
            print(f"Error inserting batch {i//batch_size + 1}: {e}")
            print("Ensure the table 'crime_data_archive' exists.")
            print("SQL to create table:")
            print("""
CREATE TABLE crime_data_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crime_type TEXT,
    location TEXT,
    coordinates JSONB,
    original_color TEXT
);
            """)
            return

    print("Import complete.")

if __name__ == "__main__":
    import_data()
