import os
import json
from supabase import create_client, Client
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")

if not url or not key:
    print("Error: SUPABASE_URL or SUPABASE_KEY not found.")
    exit(1)

supabase: Client = create_client(url, key)

def import_data():
    json_path = "frontend/src/data/war_dead_points.json"
    
    if not os.path.exists(json_path):
        print(f"Error: {json_path} not found.")
        return

    with open(json_path, 'r') as f:
        data = json.load(f)

    print(f"Read {len(data)} records from {json_path}")

    # Prepare data for insertion
    # Mapping JSON keys to table columns
    # JSON: cemetery_name, coordinates, bio_html, num_commemorated
    # Table expected: cemetery_name, coordinates, bio_html, num_commemorated
    # We will insert them as is.
    
    records_to_insert = []
    for item in data:
        records_to_insert.append({
            "cemetery_name": item["cemetery_name"],
            "coordinates": item["coordinates"], # Supabase handles JSON/Array automatically usually, or we might need to cast
            "bio_html": item["bio_html"],
            "num_commemorated": item["num_commemorated"]
        })

    # Batch insert to avoid timeouts if many records
    batch_size = 100
    for i in range(0, len(records_to_insert), batch_size):
        batch = records_to_insert[i:i+batch_size]
        try:
            response = supabase.table("war_dead_archive").insert(batch).execute()
            print(f"Inserted batch {i//batch_size + 1}")
        except Exception as e:
            print(f"Error inserting batch {i//batch_size + 1}: {e}")
            print("Ensure the table 'war_dead_archive' exists.")
            print("SQL to create table:")
            print("""
CREATE TABLE war_dead_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cemetery_name TEXT,
    coordinates JSONB,
    bio_html TEXT,
    num_commemorated INTEGER
);
            """)
            return

    print("Import complete.")

if __name__ == "__main__":
    import_data()
